---
title: "Visualization with ggplot2 Part 1"
output: html_document
---

```{r}
library(tidyverse)
library(ggridges)
```

# Load the weather data

```{r}
#rnoaa package allow to access public data online that is aggregated by the noaa.com。 就是直接可以从网站获得数据的办法
#USWOOO94728这些都是weather station
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

## Scatterplots

create my first scatterplot ever

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

New approach, same plot.

```{r}
#这个办法更好，因为可以再dataset跟ggplot之间加mutate function之类的，不需要单独再做一个新的dataframe
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

save and edit a plot object

```{r}
weather_plot =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))

weather_plot + geom_point()
  
```

## Advanced scatterplot...

Start with the same one and make it fancy!
```{r}
#geom_smooth add smooth trajectories through the data。 且出现的是多条curve，curve数量取决于name的数量（仅此题）
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() + 
  geom_smooth(se = FALSE)
```

What about the `aes` placement

```{r}
#这个办法让scatterplot跟前一个图没啥区别。但是color only applies to the scatterplot 导致smooth curve仅出现一条，不会因为name区分而出现多个
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)  
```

Let's facet some things

```{r}
#facet_grid(): create multi panel plots, function里面填写what define on rows，columns，若没有就用“."代替，若有就用“~XXXX”代替。 facet_grid 括号里面按顺序第一个works on rows， 第二个works on columns
#geom_point(alpha = 0.5) 代表ggplot里面的点需要50%transparent,还可以让alpha = 某个variable（例如alpha = tmin,就能随着tmin变化出渐变色）
#同时通过size = .3让point 小一些
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5, size = .3) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
```


